In [1]:
# pandas
# dataframe: Estructura de datos muy similar a una tabla.
# Filas y Columnas

In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 22.6 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.5.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 47.8 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.5

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [1]:
import pandas as pd

# listas: []
# diccionarios : {}
# tupla: ()

data = [['Juan', 25], ['Pedro', 34], ['Luis', 34]]

df = pd.DataFrame(data, columns=['Nombre','Edad'])

In [4]:
df

  Nombre  Edad
0   Juan    25
1  Pedro    34
2   Luis    34

In [5]:
# Crear desde un diccionario

data = {
    'Nombre': ['Juan', 'Pedro', 'Luis'],
    'Edad': [25, 26, 24]
}

df_1=pd.DataFrame(data)

In [6]:
df_1

  Nombre  Edad
0   Juan    25
1  Pedro    26
2   Luis    24

In [8]:
# leemos un archivo CSV ubicado en cierta ruta
df = pd.read_csv('utils/utils/data/data.csv')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [3]:
# Leemos un archivo sin extension y con separador distinto a la coma
df = pd.read_csv('utils/utils/data/data', sep= '|')

df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [4]:
# Leer un archivo CSV, sin cabecera
df = pd.read_csv('utils/utils/data/data_without_header',
                 sep=',',
                 header=None,
                 names=['Nombre', 'Edad', 'Ciudad'])

df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [6]:
# Leer un archivo JSON 
df = pd.read_json('utils/utils/data/data.json')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

## Metodos con Dataframes

In [7]:
# Obtener estadisticas descriptivas
df.describe()

       edad
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [8]:
# muestra top 5
df.head()

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [9]:
# muestra datos de abajo
df.tail(2)

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [10]:
#Muestra las columnas como serie
df.columns

Index(['nombre', 'edad', 'ciudad'], dtype='str')

In [11]:
# obtener todos los indices
df.index

RangeIndex(start=0, stop=3, step=1)

In [12]:
# Contabilizar registros
df.count()

nombre    3
edad      3
ciudad    3
dtype: int64

## Acceder a valores con Dataframe

In [13]:
df['ciudad']

df[['ciudad', 'edad']]

      ciudad  edad
0     Madrid    25
1  Barcelona    30
2    Sevilla    35

In [14]:
# Seleccion una fila por el indice
print(df.loc[0])

# traer multiples filas ( desde los indices 0 y 2)
print("### \n")
print(df.loc[[0, 2]])

# Siempre que cumple una condicion

print("### \n")
print(df[df['edad'] > 30])

aux = df[df['edad'] > 30]

nombre      Juan
edad          25
ciudad    Madrid
Name: 0, dtype: object
###

  nombre  edad   ciudad
0   Juan    25   Madrid
2  Pedro    35  Sevilla
###

  nombre  edad   ciudad
2  Pedro    35  Sevilla

In [15]:
aux

  nombre  edad   ciudad
2  Pedro    35  Sevilla

## Agregaciones

In [16]:
data = {
    'Grupo': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Valor': [10, 20, 15, 25, 12, 18]
}

# Convertirlo a df
df = pd.DataFrame(data)

promedio_por_grupo = df.groupby('Grupo').mean()
print(promedio_por_grupo)

suma_por_grupo = df.groupby('Grupo').sum()
print(suma_por_grupo)

           Valor
Grupo
A      12.333333
B      21.000000
       Valor
Grupo
A         37
B         63

In [17]:
# Leemos un archivo sin extension y con separador distinto a la coma
df = pd.read_csv('utils/utils/data/data', sep= '|')

df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [18]:
# Eliminar filas que contiene Nan ( desconocidos )
df_sin_nan = df.dropna()
print(df_sin_nan)

print('\n')

# reemplazar los valores faltantes
df_completo = df.fillna(value = 0)
print(df_completo)

print('\n')

# Eliminar solo las filas donde columna 'ciudad' tenga valores faltantes
df_sin_na_ciudad = df.dropna(subset=['ciudad'])
print(df_sin_na_ciudad)

print('\n')
# Reemplaza faltantes en una sola columna
df_completo_edad = df['edad'].fillna(value=0)
print(df_completo_edad)

  nombre  edad     ciudad
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


  nombre  edad     ciudad
0   Juan   0.0     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


0     0.0
1    30.0
2    35.0
Name: edad, dtype: float64

## Funciones en un Dataframe

In [19]:
data = {
    'A': [1, 2, 3, 4],
    'B': [6, 7, 8, 9]
}

df = pd.DataFrame(data)

In [20]:
# Crear una columna que multiplique por 2 los valores de A

df['A_doble'] = df['A'].apply(lambda x: x*2)

df

   A  B  A_doble
0  1  6        2
1  2  7        4
2  3  8        6
3  4  9        8

In [21]:
def multiplodos(x):
    return x*2

df['A_doble'] = df['A'].apply(multiplodos)

df

   A  B  A_doble
0  1  6        2
1  2  7        4
2  3  8        6
3  4  9        8

In [22]:
# Suma de las columnas A y B
df['Suma_metodo1'] = df.apply(lambda row: row['A'] + row['B'], axis=1)

df

   A  B  A_doble  Suma_metodo1
0  1  6        2             7
1  2  7        4             9
2  3  8        6            11
3  4  9        8            13

In [23]:
def suma(row):
    return row['A'] + row['B']

# Suma de las columnas A y B
df['Suma_metodo2'] = df.apply(suma, axis=1)

df

   A  B  A_doble  Suma_metodo1  Suma_metodo2
0  1  6        2             7             7
1  2  7        4             9             9
2  3  8        6            11            11
3  4  9        8            13            13